///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelUser {
/*
{
  "idUser": 1,
  "email": "ignacio@gmail.com"
} 
*/

  int? idUser;
  String? email;

  LoginModelUser({
    this.idUser,
    this.email,
  });
  LoginModelUser.fromJson(Map<String, dynamic> json) {
    idUser = json["idUser"]?.toInt();
    email = json["email"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["idUser"] = idUser;
    data["email"] = email;
    return data;
  }
}

class LoginModel {
/*
{
  "statusCode": 0,
  "message": "Successful login",
  "validateAuth": true,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlnbmFjaW9AZ21haWwuY29tIiwicGFzc3dvciI6InRlc3QuMjAyMSIsImlhdCI6MTYyOTgyODAxMSwiZXhwIjoxNjI5OTE0NDExfQ.8aiieyc62dZJ1JBCbIX5-N-mhJnn_5YnToUqaI51TZ8",
  "user": {
    "idUser": 1,
    "email": "ignacio@gmail.com"
  }
} 
*/

  int? statusCode;
  String? message;
  bool? validateAuth;
  String? accessToken;
  LoginModelUser? user;

  LoginModel({
    this.statusCode,
    this.message,
    this.validateAuth,
    this.accessToken,
    this.user,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    validateAuth = json["validateAuth"];
    accessToken = json["accessToken"]?.toString();
    user =
        (json["user"] != null) ? LoginModelUser.fromJson(json["user"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["statusCode"] = statusCode;
    data["message"] = message;
    data["validateAuth"] = validateAuth;
    data["accessToken"] = accessToken;
    if (user != null) {
      data["user"] = user!.toJson();
    }
    return data;
  }
}
