///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterModelUser {
/*
{
  "idUser": 5,
  "email": "alexzamudio_11@hotmail.com"
} 
*/

  int? idUser;
  String? email;

  RegisterModelUser({
    this.idUser,
    this.email,
  });
  RegisterModelUser.fromJson(Map<String, dynamic> json) {
    idUser = json["idUser"]?.toInt();
    email = json["email"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["idUser"] = idUser;
    data["email"] = email;
    return data;
  }
}

class RegisterModel {
/*
{
  "statusCode": 0,
  "message": "User registered",
  "user": {
    "idUser": 5,
    "email": "alexzamudio_11@hotmail.com"
  }
} 
*/

  int? statusCode;
  String? message;
  RegisterModelUser? user;

  RegisterModel({
    this.statusCode,
    this.message,
    this.user,
  });
  RegisterModel.fromJson(Map<String, dynamic> json) {
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    user = (json["user"] != null)
        ? RegisterModelUser.fromJson(json["user"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["statusCode"] = statusCode;
    data["message"] = message;
    if (user != null) {
      data["user"] = user!.toJson();
    }
    return data;
  }
}
